#ifndef PALAVRAS_PTBR_H
#define PALAVRAS_PTBR_H

static const char *palavras_facil[] = {
    "sol", "lua", "mar", "voo", "paz", "luz",
    "gol", "flor", "vida", "casa", "gato", "cavalo",
    "arte", "azul", "bola", "cabo", "dado", "faca",
    "fada", "fila", "fogo", "fuga", "hora", "lago",
    "lama", "leao", "lixo", "loja", "mala", "mapa",
    "mesa", "moto", "nada", "nave", "onda", "ouro",
    "papel", "pato", "pele", "pipa", "praia", "raio",
    "rato", "reto", "rico", "rosa", "sapo", "seda",
    "seta", "sino", "sopa", "tela", "tigre", "toco",
    "tubo", "vaso", "vela", "vento", "verde", "vila",
    "zebra", "ar", "eu", "tu", "ja", "oi",
    "boi", "cao", "cor", "dia", "fim", "gas",
    "ilha", "ir", "lei", "lar", "mae", "mel",
    "meu", "nao", "noz", "pai", "pao", "pao",
    "par", "pia", "pio", "pos", "rei", "rim",
    "rua", "sal", "sim", "so", "sul", "tal",
    "tio", "tom", "uva", "voz", "aqui", "ali",
    "asa", "ave", "bar", "bem", "bom", "cha",
    "chao", "cru", "dez", "dez", "dor", "flor",
    "fralda", "frio", "gado", "gelo", "grau", "isso",
    "jogo", "leve", "lobo", "mago", "mais", "mil",
    "moco", "moda", "modo", "muro", "nariz", "nave",
    "nervo", "novo", "ovo", "paco", "pao", "peixe",
    "pino", "polvo", "porta", "quase", "quilo", "ramo",
    "rede", "reino", "rima", "sede", "sopro", "tacho",
    "teto", "tigre", "toca", "topo", "torre", "trave",
    "trigo", "urso", "vale", "vime", "vaca", "vidro",
    "zorro",
};
#define NUM_FACIL (sizeof(palavras_facil) / sizeof(palavras_facil[0]))

static const char *palavras_medio[] = {
    "abelha", "amigo", "arvore", "brisa", "cachorro", "caneta",
    "carro", "chuva", "cidade", "coelho", "coragem", "cristal",
    "diamante", "espelho", "estrela", "familia", "fantasma", "floresta",
    "foguete", "girassol", "guitarra", "janela", "joaninha", "labirinto",
    "lanterna", "leitura", "liberdade", "montanha", "musica", "natureza",
    "neblina", "oceano", "pagina", "pantera", "parede", "passaro",
    "pintura", "planeta", "ponte", "portal", "quintal", "relogio",
    "riacho", "sabedoria", "sombra", "tempestade", "trovao", "universo",
    "vagalume", "viagem", "vitoria", "abraco", "aldeia", "alegria",
    "almoco", "aluno", "amizade", "aranha", "arauto", "areia",
    "armario", "aroma", "aventura", "balanco", "baleia", "banana",
    "bandeira", "barraca", "batalha", "beleza", "biblioteca", "bicicleta",
    "bolota", "bombom", "bondade", "bosque", "cachoeira", "calmaria",
    "camelo", "campeao", "canario", "caracol", "cardume", "carinho",
    "carruagem", "castelo", "caverna", "cavalaria", "cerejeira", "chamine",
    "charuto", "chocolate", "ciclone", "cinema", "circo", "clareira",
    "colcha", "colheita", "coluna", "cometa", "confianca", "coragem",
    "cortina", "costela", "coruja", "criatura", "crianca", "delicia",
    "desafio", "desenho", "destino", "dinheiro", "docura", "dragao",
    "duende", "elefante", "energia", "escola", "esconderijo", "esperanca",
    "espinho", "esqueleto", "esquilo", "estatua", "estufa", "faisca",
    "fazenda", "feiticeiro", "ferradura", "figueira", "fivela", "flauta",
    "flamingo", "fogueira", "folclore", "fonte", "formiga", "fortuna",
    "fragata", "fronteira", "fumaca", "garagem", "girafa", "gruta",
    "guardiao", "harmonia", "heroi", "horizonte", "hospital", "iceberg",
    "iguaria", "ilhota", "imagem", "impulso", "insetos", "jaqueta",
    "jardim", "jasmim", "joelho", "jornada", "labareda", "lagarto",
    "lamparina", "lavanda", "legenda", "lenda", "libelula", "limonada",
    "lousa", "luneta", "macaco", "madeira", "magia", "mandala",
    "manteiga", "maquina", "mariposa", "marfim", "melancia", "memoria",
    "mercado", "milagre", "minhoca", "misterio", "moedas", "moinho",
    "molecula", "monstro", "morango", "mosteiro", "muralha", "musgo",
    "nascente", "nevasca", "noivado", "nublado", "nuvem", "orbita",
    "orquestra", "ostra", "outono", "paisagem", "palacio", "palhaco",
    "pandeiro", "pantano", "papagaio", "paraiso", "parquinho", "passeio",
    "penhasco", "pergaminho", "pescador", "petala", "pipoca", "piquenique",
    "pirata", "poeira", "prateleira", "presente", "principe", "quintal",
    "raposa", "raiz", "raridade", "recanto", "refugio", "relampago",
    "resgate", "riacho", "riqueza", "robozinho", "rocha", "romance",
    "sacola", "saudade", "sepultura", "serpente", "silencio", "sirene",
    "soalho", "sotao", "surpresa", "tapecaria", "tartaruga", "tempero",
    "templo", "tesouro", "tigela", "torneira", "tornado", "torrada",
    "tradicao", "trenzinho", "trilha", "tulipa", "vagalume", "vampiro",
    "vantagem", "varanda", "veleiro", "verniz", "vidraca", "vinheta",
    "violino", "vulcao", "xicara", "zoologico",
};
#define NUM_MEDIO (sizeof(palavras_medio) / sizeof(palavras_medio[0]))

static const char *palavras_dificil[] = {
    "abobora", "acontecimento", "aeronave", "arquitetura", "astronauta", "borboleta",
    "civilizacao", "computador", "conhecimento", "constelacao", "descoberta", "eletricidade",
    "engenharia", "experiencia", "felicidade", "gravidade", "imaginacao", "independencia",
    "labirintico", "matematica", "meteorito", "microscopio", "observatorio", "oportunidade",
    "paralelepipedo", "quantidade", "responsabilidade", "revolucao", "tecnologia", "telescopio",
    "transformacao", "tranquilidade", "universidade", "velocidade", "extraterrestre", "hipopotamo",
    "impossivel", "invisibilidade", "acompanhamento", "administracao", "agradecimento", "alfabetizacao",
    "aniversario", "aposentadoria", "aprendizagem", "arrependimento", "articulacao", "assombracao",
    "atmosfera", "automovel", "biblioteca", "brincadeira", "burocracia", "caracteristica",
    "cerimonia", "circunstancia", "coincidencia", "colaboracao", "comemoracao", "competicao",
    "comunidade", "concentracao", "confirmacao", "consciencia", "consequencia", "constituicao",
    "contabilidade", "contribuicao", "coordenacao", "criatividade", "curiosidade", "declaracao",
    "demonstracao", "desenvolvimento", "diversidade", "dificuldade", "eletromagnetico", "eliminacao",
    "emocionante", "espetaculo", "estabilidade", "estrategico", "exclamacao", "explicacao",
    "extraordinario", "fenomeno", "fortalecimento", "fotografia", "generosidade", "governanca",
    "identidade", "iluminacao", "imunologia", "inaugurar", "inesquecivel", "informacao",
    "inteligencia", "interpretacao", "investigacao", "linguistica", "maravilhoso", "mecanismo",
    "microorganismo", "multiplicacao", "necessidade", "negociacao", "observacao", "organizacao",
    "paleontologo", "participacao", "personagem", "planejamento", "populacao", "possibilidade",
    "preservacao", "probabilidade", "processamento", "profissional", "protagonista", "publicacao",
    "qualificacao", "reciclagem", "reconhecimento", "recuperacao", "representacao", "reproducao",
    "significado", "simplicidade", "sinceridade", "sofisticado", "sustentavel", "temperatura",
    "transparencia", "vulnerabilidade",
};
#define NUM_DIFICIL (sizeof(palavras_dificil) / sizeof(palavras_dificil[0]))

static const char *palavras_espaco[] = {
    "asteroide", "buraco negro", "cometa", "constelacao", "eclipse", "estrela",
    "galaxia", "lua", "marte", "meteoro", "nebulosa", "orbita",
    "planeta", "satelite", "saturno", "sistema solar", "sol", "supernova",
    "universo", "via lactea", "foguete", "astronauta", "nave", "jupiter",
    "venus", "mercurio", "netuno", "urano", "plutao", "terra",
    "estacao espacial", "modulo lunar", "telescopio", "gravidade zero", "capsula", "combustivel",
    "lancamento", "orbita terrestre", "quasar", "buraco de minhoca", "meteorito", "cinturao de asteroides",
    "cometa halley", "estrela cadente", "sonda espacial", "radiacao cosmica", "vacuo", "atmosfera",
    "aterrissagem", "decolagem", "painel solar", "robo explorador",
};
#define NUM_ESPACO (sizeof(palavras_espaco) / sizeof(palavras_espaco[0]))

static const char *palavras_animais[] = {
    "cachorro", "gato", "elefante", "girafa", "leao", "tigre",
    "urso", "macaco", "zebra", "cavalo", "vaca", "porco",
    "galinha", "pato", "coelho", "raposa", "lobo", "esquilo",
    "morcego", "aguia", "coruja", "papagaio", "tucano", "flamingo",
    "pinguim", "golfinho", "baleia", "tubarao", "polvo", "tartaruga",
    "crocodilo", "jacare", "cobra", "lagarto", "sapo", "aranha",
    "escorpiao", "formiga", "abelha", "borboleta", "libelula", "besouro",
    "camaleao", "canguru", "coala", "panda", "rinoceronte", "hipopotamo",
    "gorila", "chimpanze", "lhama", "avestruz", "pavao", "gaivota",
    "pelicano", "salamandra", "ourico",
};
#define NUM_ANIMAIS (sizeof(palavras_animais) / sizeof(palavras_animais[0]))

static const char *palavras_tecnologia[] = {
    "computador", "celular", "internet", "software", "aplicativo", "teclado",
    "monitor", "impressora", "servidor", "algoritmo", "programacao", "inteligencia artificial",
    "robotica", "sensor", "bateria", "processador", "memoria", "arquivo",
    "download", "upload", "senha", "usuario", "codigo", "sistema",
    "rede", "wifi", "bluetooth", "camera", "microfone", "fone de ouvido",
    "carregador", "notebook", "tablet", "drone", "chip", "circuito",
    "antena", "satelite", "streaming", "nuvem", "backup",
};
#define NUM_TECNOLOGIA (sizeof(palavras_tecnologia) / sizeof(palavras_tecnologia[0]))

#endif /* PALAVRAS_PTBR_H */